[package]
name = "PHPantomLSP"
version = "0.1.0"
edition = "2024"

[dependencies]
tower-lsp = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
tokio = { version = "1.34", features = ["full"] }
