id = "phpantom"
name = "PHPantom"
description = "PHP language support powered by PHPantom LSP â€” a fast, lightweight PHP language server."
version = "0.0.1"
schema_version = 1
authors = ["AJenbo <anders@jenbo.dk>"]
repository = "https://github.com/AJenbo/phpantom_lsp"

[language_servers.phpantom_lsp]
name = "PHPantom LSP"
languages = ["PHP"]
language_ids = { PHP = "php" }
