id = "phpantom"
name = "PHPantom"
description = "PHP language support powered by PHPantom LSP, a fast and lightweight PHP language server."
version = "0.3.0"
schema_version = 1
authors = ["Anders Jenbo <anders@jenbo.dk>"]
repository = "https://github.com/AJenbo/phpantom_lsp"

[language_servers.phpantom_lsp]
name = "PHPantom"
languages = ["PHP"]
language_ids = { PHP = "php" }
